version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    allow:
      - dependency-type: "direct"
    schedule:
      interval: "daily"
    versioning-strategy: "increase"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
